### PR TITLE
Revert "Enable hwcomposer"

### PR DESCRIPTION
**Pull request by ldts**
Reverts 96boards/android_device_linaro_hikey#6

### CODE REVIEW

**Comment by vishalbhoj** [comment]
Any specific reason to merge and then revert ? This needs to be merged along with  the kernel bits.

**Comment by ldts** [comment]
On 06/17/2015 11:51 PM, vishalbhoj wrote:

> Any specific reason to merge and then revert ? This needs to be merged along with  the kernel bits.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/96boards/android_device_linaro_hikey/pull/8#issuecomment-113027213

actually I merged by mistake so I reverted (I was following the link from the
kernel commit); it is scary how easy is to mess up things using this gui...I
tend to use the console.anyway.
Now that I have merged the kernel changes I can revert the revert on this
project (or maybe you want to do it?)

**Comment by ldts** [comment]
ok done - revert reverted.

**Comment by xin3liang** [comment]
Hello idts,  according your words, it seems that there is something wrong with this patch.Could you explain it clearly? What do you mean by "it is scary how easy is to mess up things using this gui...I
tend to use the console.anyway." i don't catch your point, sorry.

**Comment by ldts** [comment]
Hi @xin3liang, sorry no I meant that I merged too early by mistake so I reverted the merge. After I committed the required kernel changes I reverted the revert so everything should be set.  I hope this clarifies.

**Comment by xin3liang** [comment]
Ok, got it! Thanks.

**Pull request merged**
